<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.datasteel.crudcraft</groupId>
        <artifactId>crudcraft-parent</artifactId>
        <version>2.0.1</version>
    </parent>
    <artifactId>crudcraft-codegen</artifactId>
    <packaging>jar</packaging>
    <name>CrudCraft Codegen</name>

    <properties>
        <crudcraft.automatic.module.name>nl.datasteel.crudcraft.codegen</crudcraft.automatic.module.name>
    </properties>

    <dependencies>
        <!-- Annotation API -->
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>

        <!-- JavaPoet -->
        <dependency>
            <groupId>com.palantir.javapoet</groupId>
            <artifactId>javapoet</artifactId>
        </dependency>

        <dependency>
            <groupId>nl.datasteel.crudcraft</groupId>
            <artifactId>crudcraft-api</artifactId>
        </dependency>

        <!-- OpenAPI annotations for generated API documentation -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
        </dependency>

        <!-- Jackson annotations for generated DTOs -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>com.google.testing.compile</groupId>
            <artifactId>compile-testing</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Jakarta Persistence API for relationships-->
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>nl.datasteel.crudcraft</groupId>
            <artifactId>crudcraft-runtime-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>nl.datasteel.crudcraft</groupId>
            <artifactId>crudcraft-runtime-search</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>nl.datasteel.crudcraft</groupId>
            <artifactId>crudcraft-runtime-export</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>nl.datasteel.crudcraft</groupId>
            <artifactId>crudcraft-runtime-extensions</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>nl.datasteel.crudcraft</groupId>
            <artifactId>crudcraft-runtime-projection</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>nl.datasteel.crudcraft</groupId>
            <artifactId>crudcraft-runtime-security</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.spotbugs</groupId>
            <artifactId>spotbugs-annotations</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Ensure this is picked up as an annotation-processor -->
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <!-- Inherits config from parent -->
                <configuration>
                    <proc>none</proc>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <crudcraft.golden.update>${crudcraft.golden.update}</crudcraft.golden.update>
                    </systemPropertyVariables>
                    <argLine>
                        @{argLine}
                        ${mockito.agent.arg}
                        -Xshare:off
                        --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
                        --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
                        --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
                        --add-exports jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <doclint>none</doclint>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>${maven.enforcer.plugin.version}</version>
                <executions>
                    <execution>
                        <id>ban-runtime-on-codegen-classpath</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <bannedDependencies>
                                    <searchTransitive>false</searchTransitive>
                                    <excludes>
                                        <exclude>nl.datasteel.crudcraft:crudcraft-runtime:*:*:compile</exclude>
                                        <exclude>nl.datasteel.crudcraft:crudcraft-runtime-core:*:*:compile</exclude>
                                        <exclude>nl.datasteel.crudcraft:crudcraft-runtime-search:*:*:compile</exclude>
                                        <exclude>nl.datasteel.crudcraft:crudcraft-runtime-export:*:*:compile</exclude>
                                        <exclude>nl.datasteel.crudcraft:crudcraft-runtime-projection:*:*:compile</exclude>
                                        <exclude>nl.datasteel.crudcraft:crudcraft-runtime-security:*:*:compile</exclude>
                                        <exclude>nl.datasteel.crudcraft:crudcraft-runtime-extensions:*:*:compile</exclude>
                                    </excludes>
                                </bannedDependencies>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Enables the codegen to inject the CrudCraft version into the file headers -->
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <version>${maven.jar.plugin.version}</version>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Implementation-Version>${project.version}</Implementation-Version>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <configuration>
                    <parseSurefireArgLine>false</parseSurefireArgLine>
                    <jvmArgs>
                        <jvmArg>${mockito.agent.arg}</jvmArg>
                        <jvmArg>-Xshare:off</jvmArg>
                        <jvmArg>--add-exports</jvmArg>
                        <jvmArg>jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</jvmArg>
                        <jvmArg>--add-exports</jvmArg>
                        <jvmArg>jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</jvmArg>
                        <jvmArg>--add-exports</jvmArg>
                        <jvmArg>jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</jvmArg>
                        <jvmArg>--add-exports</jvmArg>
                        <jvmArg>jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</jvmArg>
                    </jvmArgs>
                </configuration>
                <executions>
                    <execution>
                        <id>pitest-codegen-descriptor-field</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/descriptor-field</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.RelationshipType</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.field.*</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.field.part.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.DtoOptionsTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.EnumOptionsTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.FieldDescriptorTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.IdentityPartTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.RelationshipPartTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.RelationshipTypeTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.SchemaMetadataTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.SearchOptionsTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.SecurityPartTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.SecurityTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.ValidationPartTest</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-descriptor-model</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/descriptor-model</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.model.*</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.model.part.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.EndpointOptionsTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.ModelDescriptorTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.ModelFlagsTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.ModelIdentityTest</param>
                                <param>nl.datasteel.crudcraft.codegen.descriptor.ModelSecurityTest</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-exception</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <skip>true</skip>
                            <reportsDirectory>${project.build.directory}/pit-reports/exception</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.exception.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.exception.*Test</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-fileheader</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/fileheader</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.fileheader.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.fileheader.*Test</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-util</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/util</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.util.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.util.*Test</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-reader</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/reader</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.reader.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.reader.*Test</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-processors</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/processors</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.CrudCraftProcessor</param>
                                <param>nl.datasteel.crudcraft.codegen.projection.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.CrudCraftProcessorTest</param>
                                <param>nl.datasteel.crudcraft.codegen.projection.*Test</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-writer-dto</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/writer-dto</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.writer.DtoGenerator</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.DtoType</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.writer.DtoGenerator*Test</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.DtoTypeTest</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-writer-search-generator</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/writer-search-generator</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.writer.SearchGenerator</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.writer.SearchGeneratorTest</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-writer-infra</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/writer-infra</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.writer.Generator</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.InsomniaGenerator</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.TemplateUtil</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.WriteContext</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.WriterRegistry</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.writer.GeneratorTest</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.InsomniaGeneratorTest</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.TemplateUtilTest</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.WriteContextTest</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.WriterRegistryTest</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-writer-controller</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/writer-controller</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.writer.controller.*</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.controller.endpoints.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.writer.controller.*Test</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.controller.endpoints.*Test</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-writer-search</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/writer-search</reportsDirectory>
                            <threads>4</threads>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.writer.search.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.writer.search.*Test</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.SearchGeneratorTest</param>
                            </targetTests>
                        </configuration>
                    </execution>
                    <execution>
                        <id>pitest-codegen-writer-stubs</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                        <configuration>
                            <reportsDirectory>${project.build.directory}/pit-reports/writer-stubs</reportsDirectory>
                            <targetClasses>
                                <param>nl.datasteel.crudcraft.codegen.writer.RelationshipMetaGenerator</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.relationship.*</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.stubs.*</param>
                            </targetClasses>
                            <targetTests>
                                <param>nl.datasteel.crudcraft.codegen.writer.RelationshipMetaGeneratorTest</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.relationship.*Test</param>
                                <param>nl.datasteel.crudcraft.codegen.writer.stubs.*Test</param>
                            </targetTests>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>golden-update</id>
            <properties>
                <crudcraft.golden.update>true</crudcraft.golden.update>
            </properties>
        </profile>
    </profiles>
</project>
