<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.datasteel.crudcraft</groupId>
        <artifactId>crudcraft-parent</artifactId>
        <version>2.0.0</version>
    </parent>
    <artifactId>crudcraft-runtime-extensions</artifactId>
    <packaging>jar</packaging>
    <name>CrudCraft Runtime Extensions</name>

    <properties>
        <crudcraft.automatic.module.name>nl.datasteel.crudcraft.runtime.extensions</crudcraft.automatic.module.name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>nl.datasteel.crudcraft</groupId>
            <artifactId>crudcraft-runtime-core</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <configuration>
                    <linkXRef>false</linkXRef>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <configuration>
                    <targetClasses>
                        <targetClass>nl.datasteel.crudcraft.runtime.extensions.*</targetClass>
                        <targetClass>nl.datasteel.crudcraft.runtime.util.*</targetClass>
                    </targetClasses>
                    <targetTests>
                        <targetTest>nl.datasteel.crudcraft.runtime.extensions.*</targetTest>
                        <targetTest>nl.datasteel.crudcraft.runtime.util.*</targetTest>
                    </targetTests>
                </configuration>
                <executions>
                    <execution>
                        <id>pitest</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
