<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.datasteel.crudcraft</groupId>
        <artifactId>crudcraft-parent</artifactId>
        <version>2.0.0</version>
    </parent>
    <artifactId>crudcraft-api</artifactId>
    <packaging>jar</packaging>
    <name>CrudCraft API</name>

    <properties>
        <crudcraft.automatic.module.name>nl.datasteel.crudcraft.api</crudcraft.automatic.module.name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <executions>
                    <execution>
                        <id>pitest-mutation-check</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>mutationCoverage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <targetClasses>
                        <param>nl.datasteel.crudcraft.annotations.*</param>
                        <param>nl.datasteel.crudcraft.annotations.security.*</param>
                    </targetClasses>
                    <targetTests>
                        <param>nl.datasteel.crudcraft.annotations.*Test</param>
                        <param>nl.datasteel.crudcraft.annotations.security.*Test</param>
                    </targetTests>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
