name: CI

on:
  pull_request:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review, labeled]
  push:
    branches: [ main, 'maintenance/*' ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: CI / build
    runs-on: ubuntu-latest

    steps:
      # For pull_request_target we must explicitly check out the PR HEAD commit
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || '' }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compile & test
        run: mvn -B -U -Dstyle.color=always verify
