name: Dispatch docs deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  trigger-deployer:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to deployer repo
        env:
          GH_TOKEN: ${{ secrets.DOCS_DISPATCH_TOKEN }}
          OWNER: your-org-or-user
          REPO: CrudCraft-Docs-Deployer
          EVENT: crudcraft-updated
        run: |
          set -euo pipefail
          payload=$(cat <<JSON
          {
            "sha": "$GITHUB_SHA",
            "ref": "$GITHUB_REF_NAME",
            "repo": "$GITHUB_REPOSITORY",
            "pushed_by": "$GITHUB_ACTOR"
          }
          JSON
          )
          curl -sS -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/dispatches \
            -d "{\"event_type\":\"$EVENT\",\"client_payload\":$payload}"