name: Release to Maven Central

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: central
          server-username: ${{ secrets.CENTRAL_USERNAME }}
          server-password: ${{ secrets.CENTRAL_PASSWORD }}
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.SIGNING_PASSWORD }}

      - name: Set version from tag (no -SNAPSHOT)
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          mvn -B versions:set -DnewVersion="$TAG" -DgenerateBackupPoms=false

      - name: Verify (tests)
        run: mvn -B -U -Dstyle.color=always verify

      - name: Deploy release artifacts (signed + staged + auto-release)
        run: mvn -B -P release -Dstyle.color=always -DskipTests=false deploy

