name: Release Please

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  release-please:
    name: Release-PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          command: manifest
          target-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
