name: Release Please

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-please
  cancel-in-progress: true

jobs:
  release-please:
    name: Release-PR
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          command: manifest
          target-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
