name: Release to Maven Central

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # JDK + import GPG private key for signing (release profile)
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          gpg-passphrase:  ${{ secrets.SIGNING_PASSWORD }}

      # Provide env vars that settings.xml will reference
      - name: Export env for Central auth & GPG
        run: |
          echo "CENTRAL_USERNAME=${{ secrets.CENTRAL_USERNAME }}" >> $GITHUB_ENV
          echo "CENTRAL_PASSWORD=${{ secrets.CENTRAL_PASSWORD }}" >> $GITHUB_ENV

      - name: Write settings.xml (explicit)
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
            <servers>
              <server>
                <id>central</id>
                <username>${env.CENTRAL_USERNAME}</username>
                <password>${env.CENTRAL_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          XML

      - name: Set version from tag
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          mvn -B versions:set -DnewVersion="$TAG" -DgenerateBackupPoms=false

      - name: Verify (tests + build)
        run: mvn -B -U -Dstyle.color=always verify

      - name: Deploy (publish to Central)
        run: mvn -B -P release -Dstyle.color=always -DskipTests=false deploy
