name: Release to Maven Central

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.SIGNING_PASSWORD }}

      - name: Set version from tag
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          mvn -B versions:set -DnewVersion="$TAG" -DgenerateBackupPoms=false

      - name: Deploy release artifacts
        run: mvn -B -P release -DskipTests deploy
