name: Enforce Conventional Commits

on:
  pull_request_target:

jobs:
  semantic:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      statuses: write

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
            test
          scopes: |
            runtime
            codegen
            docs
            projection
            security
            sample-app
            tools
            other
          requireScope: false
          subjectPattern: ^.+$
          wip: true
