name: Snapshot Deploy

on:
  push:
    branches: [ main, 'maintenance/*' ]

permissions:
  contents: read

concurrency:
  group: snapshot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snapshot:
    name: Deploy SNAPSHOTs
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Export env for Maven auth
        run: |
          echo "CENTRAL_USERNAME=${{ secrets.CENTRAL_USERNAME }}" >> $GITHUB_ENV
          echo "CENTRAL_PASSWORD=${{ secrets.CENTRAL_PASSWORD }}" >> $GITHUB_ENV

      - name: Write settings.xml (explicit)
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<'XML'
          <settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
            <servers>
              <server>
                <id>central</id>
                <username>${env.CENTRAL_USERNAME}</username>
                <password>${env.CENTRAL_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          XML

      - name: Set snapshot version
        run: mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)-SNAPSHOT

      - name: Verify (tests)
        run: mvn -B -U -Dstyle.color=always verify

      - name: Deploy SNAPSHOTs
        run: mvn -B -U -Dstyle.color=always -DskipTests=false deploy
