name: Snapshot Deploy

on:
  push:
    branches: [develop]

permissions:
  contents: read

concurrency:
  group: snapshot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snapshot:
    name: Deploy SNAPSHOTs
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          server-id: central
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.SIGNING_PASSWORD }}

      - name: Verify (tests)
        run: mvn -B -U -Dstyle.color=always verify

      - name: Deploy SNAPSHOTs
        run: mvn -B -Dstyle.color=always -DskipTests=false deploy
